# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e940ed3c29c1acb7a83d9c9c2aa6716662d745c7cb2c92e9f65246056bcd2856b9af797607fa0263748657dc95a6baf190a7c8c4f56daeac2c23f2416c36ee09

test:
  secret_key_base: 8cecadf917da6b1686f579fcafd8c7b0fe01bc4abe610e6e7cf00e07e64218fe9994152efa9a3deaa4996b828901566e33c7f61e1a6ca4f97f335324ba9b2777

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
